services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/vocation261/akuma-bot:latest
    container_name: akuma-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
