services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: prod-akuma-bot
    container_name: prod-akuma-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
