services:
  bot-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: dev-botkumax
    container_name: dev-botkumax
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - ./src:/app/src
      - ./data-dev:/app/data
      - ./.env.dev:/app/.env:ro
